#!/usr/bin/env python3
"""anonymize_paper.py — produce the camera-ready-anonymized variant.

Reads papers/f2_methodology.md and emits
papers/f2_methodology_anonymized.md with identifying strings replaced.
Substitutions follow the anonymization checklist at
papers/tmlr_submission_kit/anonymization_checklist.md:

  - Loop NN references          → "(internal ref)"
  - Specific git SHAs           → "[anchor]"
  - Branch name `f2-methodology` → "[branch]"
  - §10.3 Acknowledgments body  → "[OMITTED FOR DOUBLE-BLIND REVIEW]"
  - "primary maintainer" / "autonomous-research agent" phrases → stripped

The script is idempotent and produces no warnings on clean text. After
acceptance, run the script in reverse on the camera-ready content (or
just re-publish the non-anonymized source).

Usage: papers/scripts/anonymize_paper.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parents[2]
SRC = CRATE_ROOT / "papers" / "f2_methodology.md"
DST = CRATE_ROOT / "papers" / "f2_methodology_anonymized.md"


# Known git SHAs from the paper (manually catalogued at Loop 67).
KNOWN_SHAS = (
    "5367bde", "ae48fd5", "19d032e", "a092d5e", "be9b4c4",
    "2904108", "5c33083", "5f32933", "43d5d33", "77d1218",
    "ccbf52b", "05f37cd", "2969bdf", "76048b5", "dea2723",
    "583b417", "6f20c90",
)


def anonymize(text: str) -> str:
    # Loop N / Loop NN references — strip parenthetical and inline forms.
    text = re.sub(r"\(Loop \d+(?:[a-z]?)\)", "", text)
    text = re.sub(r"\(Loop \d+ [^)]*\)", "", text)
    text = re.sub(r"\(Loops? \d+(?:[ ,-]+\d+)*\)", "", text)
    text = re.sub(r"\bLoops? \d+(?:[ ,-]+\d+)*\b", "(internal ref)", text)
    # Specific known SHAs.
    for sha in KNOWN_SHAS:
        text = text.replace(sha, "[anchor]")
    # Branch name.
    text = re.sub(r"\bf2-methodology\b", "[branch]", text)
    text = re.sub(r"`f2-methodology`", "`<branch>`", text)
    # Repo path traces that may leak through.
    text = text.replace("gHashTag/trios-trainer-igla", "<anonymous-repo>")
    text = text.replace("trios-railway", "<anonymous-repo>")
    text = text.replace("/Users/playra/", "/<user>/")
    # §10.3 Acknowledgments — replace body with omission notice.
    text = re.sub(
        r"### 10\.3 Acknowledgments \+ funding disclosure\n\n.*?(?=\n### |\Z)",
        "### 10.3 Acknowledgments + funding disclosure\n\n"
        "[OMITTED FOR DOUBLE-BLIND REVIEW. Restored at camera-ready.]\n\n",
        text,
        flags=re.DOTALL,
    )
    # "autonomous-research agent" / "primary maintainer" stripping.
    text = re.sub(
        r"autonomous-research agent under the guidance of "
        r"the F2 framework's primary maintainer\.",
        "the authors.",
        text,
    )
    # Double-space cleanup from the strips above. Preserve leading
    # whitespace (list-item continuation depends on 3-space indent), so
    # only collapse runs of >=2 spaces that follow a non-whitespace.
    text = re.sub(r"(?<=\S) {2,}", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def main() -> int:
    src_text = SRC.read_text()
    out_text = anonymize(src_text)
    # Add a banner at the top.
    banner = (
        "<!-- ANONYMIZED VARIANT — auto-generated by "
        "papers/scripts/anonymize_paper.py. Do not edit by hand. "
        "Modify papers/f2_methodology.md and re-run the script. -->\n\n"
    )
    DST.write_text(banner + out_text)

    # Sanity check: should be zero identifying strings remaining.
    identifying = re.compile(
        r"gHashTag|playra|trios-railway|@anthropic\.com|@claude\.com"
        r"|Co-Authored-By"
    )
    matches = identifying.findall(out_text)
    if matches:
        print(
            f"# WARN: {len(matches)} identifying strings remain in "
            f"{DST.relative_to(CRATE_ROOT)}",
            file=sys.stderr,
        )
        print(f"# matches: {sorted(set(matches))}", file=sys.stderr)
        return 1

    src_lines = src_text.count("\n")
    dst_lines = out_text.count("\n")
    print(
        f"# Wrote {DST.relative_to(CRATE_ROOT)} "
        f"({dst_lines} lines, source was {src_lines})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
