#!/usr/bin/env python3
"""cross_reference_audit.py — verify every cross-reference in the paper.

Three categories of refs checked:
  1. Internal §X.Y section references — must resolve to a `## ` or `### ` header
  2. arXiv citations — must be syntactically valid (NNNN.NNNNN format)
  3. Binary / file mentions — must resolve to a real file under crate root

Output: papers/cross_reference_report.md
Exit: 0 always (informational).

Usage: papers/scripts/cross_reference_audit.py
"""

from __future__ import annotations

import datetime as _dt
import os
import re
import sys
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parents[2]
PAPER = CRATE_ROOT / "papers" / "f2_methodology.md"
OUT = CRATE_ROOT / "papers" / "cross_reference_report.md"

SECTION_REF_RE = re.compile(r"§(\d+(?:\.\d+){0,2})")
ARXIV_RE = re.compile(r"arXiv:(\d{4}\.\d{4,5})")
BACKTICK_FILE_RE = re.compile(r"`([A-Za-z0-9_./-]+\.(?:rs|toml|md|csv|sh|png|py|jsonl))`")
BACKTICK_FILE_GROUP_IDX = 1
BARE_BIN_RE = re.compile(r"`(f2_[a-z_]+)`")
HEADER_2_RE = re.compile(r"^##\s+(\d+(?:\.\d+)?)\.")
HEADER_3_RE = re.compile(r"^###\s+(\d+\.\d+(?:\.\d+)?)")
INLINE_BOLD_3_RE = re.compile(r"\*\*(\d+\.\d+\.\d+)")


def main() -> int:
    if not PAPER.exists():
        print(f"ERROR: {PAPER} not found", file=sys.stderr)
        return 1

    text = PAPER.read_text()
    lines = text.splitlines()

    defined_sections: set[str] = set()
    for line in lines:
        m = HEADER_2_RE.match(line)
        if m:
            defined_sections.add(m.group(1))
        m = HEADER_3_RE.match(line)
        if m:
            sec = m.group(1)
            defined_sections.add(sec)
            # Also register the bare top-level for §X notation.
            parts = sec.split(".")
            if len(parts) >= 2:
                defined_sections.add(parts[0])
        m = INLINE_BOLD_3_RE.search(line)
        if m:
            defined_sections.add(m.group(1))
            # parent §X.Y is implicit
            parent = ".".join(m.group(1).split(".")[:2])
            defined_sections.add(parent)

    section_first_seen: dict[str, int] = {}
    arxiv_first_seen: dict[str, int] = {}
    file_first_seen: dict[str, int] = {}
    bin_first_seen: dict[str, int] = {}
    dangling_sections: list[str] = []
    dangling_arxiv: list[str] = []
    dangling_files: list[str] = []

    for idx, line in enumerate(lines, start=1):
        for sec in SECTION_REF_RE.findall(line):
            if sec not in section_first_seen:
                section_first_seen[sec] = idx
                if sec not in defined_sections:
                    dangling_sections.append(f"§{sec} at line {idx}")
        for arx in ARXIV_RE.findall(line):
            if arx not in arxiv_first_seen:
                arxiv_first_seen[arx] = idx
                if not re.fullmatch(r"\d{4}\.\d{4,5}", arx):
                    dangling_arxiv.append(f"arXiv:{arx} at line {idx} (malformed)")
        for match in BACKTICK_FILE_RE.finditer(line):
            path = match.group(BACKTICK_FILE_GROUP_IDX)
            if path in file_first_seen:
                continue
            file_first_seen[path] = idx
            if path.startswith("/tmp/") or path.startswith("/"):
                continue
            full = CRATE_ROOT / path
            if not full.exists():
                dangling_files.append(f"{path} at line {idx}")
        for bin_name in BARE_BIN_RE.findall(line):
            if bin_name not in bin_first_seen:
                bin_first_seen[bin_name] = idx
                bin_exists = (CRATE_ROOT / "src" / "bin" / f"{bin_name}.rs").exists()
                suite_exists = (CRATE_ROOT / "tests" / f"{bin_name}.rs").exists()
                if not bin_exists and not suite_exists:
                    dangling_files.append(
                        f"binary {bin_name} at line {idx} "
                        f"(no src/bin/{bin_name}.rs or tests/{bin_name}.rs)"
                    )

    when = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body: list[str] = []
    body.append("# Cross-reference audit — `papers/f2_methodology.md`")
    body.append("")
    body.append(
        f"_Auto-generated by `papers/scripts/cross_reference_audit.py` at {when}._"
    )
    body.append("")
    body.append("## Summary")
    body.append("")
    body.append(f"- Unique section references seen: {len(section_first_seen)}")
    body.append(f"- Unique arXiv citations seen: {len(arxiv_first_seen)}")
    body.append(
        f"- Unique file/binary references seen: {len(file_first_seen) + len(bin_first_seen)}"
    )
    body.append(f"- Dangling section references: {len(dangling_sections)}")
    body.append(f"- Malformed arXiv citations: {len(dangling_arxiv)}")
    body.append(f"- Missing files/binaries: {len(dangling_files)}")
    body.append("")

    if dangling_sections:
        body.append("## Dangling section references")
        body.append("")
        body.extend(f"- `{e}`" for e in dangling_sections)
        body.append("")
    if dangling_arxiv:
        body.append("## Malformed arXiv citations")
        body.append("")
        body.extend(f"- `{e}`" for e in dangling_arxiv)
        body.append("")
    if dangling_files:
        body.append("## Missing files / binaries")
        body.append("")
        body.extend(f"- `{e}`" for e in dangling_files)
        body.append("")
    if not (dangling_sections or dangling_arxiv or dangling_files):
        body.append("## All clear")
        body.append("")
        body.append("Every reference in the paper resolves.")
        body.append("")

    body.append("## All arXiv citations seen")
    body.append("")
    for arx in sorted(arxiv_first_seen):
        body.append(f"- arXiv:{arx} (first at line {arxiv_first_seen[arx]})")
    body.append("")
    body.append("## All section references seen")
    body.append("")
    for sec in sorted(section_first_seen, key=lambda s: [int(p) for p in s.split(".")]):
        body.append(f"- §{sec} (first at line {section_first_seen[sec]})")
    body.append("")
    body.append("## All binary references seen")
    body.append("")
    for bin_name in sorted(bin_first_seen):
        body.append(f"- `{bin_name}` (first at line {bin_first_seen[bin_name]})")
    body.append("")

    OUT.write_text("\n".join(body))
    total = len(dangling_sections) + len(dangling_arxiv) + len(dangling_files)
    print(f"# Wrote {OUT.relative_to(CRATE_ROOT)} — dangling refs: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
