#!/usr/bin/env bash
# generate_appendix_d.sh — auto-generate the paper's Appendix D test inventory.
#
# Runs `cargo test --list` on every F2 binary + integration suite + the lib,
# parses the test names, and emits a Markdown table grouped by suite.
#
# Output is written to `papers/appendix_d_test_inventory.md`. The intent is
# for the paper's §11 Appendix D to either inline this file or reference it.
#
# Usage:
#   ./papers/scripts/generate_appendix_d.sh
#
# No arguments. Reads `Cargo.toml` to discover binaries and integration tests.

set -euo pipefail

CRATE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$CRATE_ROOT"

OUT="papers/appendix_d_test_inventory.md"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# All F2 binary targets (the ones the paper documents).
F2_BINS=(
    f2_ablation_aggregate
    f2_ablation_sweep
    f2_dual_mediation
    f2_iloco_dot
    f2_iloco_score
    f2_mediation
    f2_mediation_sensitivity
    f2_provenance_check
    f2_stratum_compare
    f2_to_jsonl
)

# Integration test suites under tests/.
INT_TESTS=(
    f2_ablation_pipeline_e2e
    f2_dual_mediation_preamble
    f2_label_convention
    f2_provenance_check_exit_codes
    f2_three_stratum_pipeline_e2e
    f2_warmup_stratified_e2e
    f2_wd_stratified_e2e
)

list_lib_tests() {
    cargo test --lib --no-run --quiet > /dev/null 2>&1
    cargo test --lib -- --list --format=terse 2>/dev/null \
        | awk '/: test$/ { sub(/: test$/, ""); print }' \
        | sort -u
}

list_bin_tests() {
    local bin="$1"
    cargo test --bin "$bin" --no-run --quiet > /dev/null 2>&1 || return 0
    cargo test --bin "$bin" -- --list --format=terse 2>/dev/null \
        | awk '/: test$/ { sub(/: test$/, ""); print }' \
        | sort -u
}

list_int_tests() {
    local suite="$1"
    cargo test --test "$suite" --no-run --quiet > /dev/null 2>&1 || return 0
    cargo test --test "$suite" -- --list --format=terse 2>/dev/null \
        | awk '/: test$/ { sub(/: test$/, ""); print }' \
        | sort -u
}

emit_section() {
    local title="$1"
    local source="$2"
    shift 2
    local tests=("$@")
    local n=${#tests[@]}
    if [[ $n -eq 0 ]]; then
        return
    fi
    echo "" >> "$OUT"
    echo "### $title" >> "$OUT"
    echo "" >> "$OUT"
    echo "_$n tests, source: \`$source\`_" >> "$OUT"
    echo "" >> "$OUT"
    echo "| # | Test name |" >> "$OUT"
    echo "|---|-----------|" >> "$OUT"
    local i=1
    for t in "${tests[@]}"; do
        echo "| $i | \`$t\` |" >> "$OUT"
        i=$((i+1))
    done
}

# Header.
cat > "$OUT" <<HDR
# Appendix D — F2 Test Inventory

_Auto-generated by \`papers/scripts/generate_appendix_d.sh\` at $(date -u +%Y-%m-%dT%H:%M:%SZ)._

This appendix lists every test that backs a claim in the main paper.
Tests are grouped by source (lib, per-binary unit tests, integration
suites under \`tests/\`).

Total counts:
- Library: see lib section below
- Per-binary unit tests: see each binary section below
- Integration suites under \`tests/\`: see integration sections below

Run all of them with \`cargo test\` from the crate root; the
\`papers/f2_methodology.md\` §3.5.4 reviewer-reproducibility checklist
asserts \`cargo test --lib\` exits zero with the documented passing count
at the anchor commit.

HDR

# Lib section.
lib_tests=()
while IFS= read -r line; do
    [[ -n "$line" ]] && lib_tests+=("$line")
done < <(list_lib_tests || true)
emit_section "Library (\`src/lib.rs\`)" "cargo test --lib" "${lib_tests[@]+"${lib_tests[@]}"}"

# Per-binary sections.
for bin in "${F2_BINS[@]}"; do
    bin_tests=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && bin_tests+=("$line")
    done < <(list_bin_tests "$bin" || true)
    emit_section "Binary \`$bin\`" "cargo test --bin $bin" "${bin_tests[@]+"${bin_tests[@]}"}"
done

# Integration sections.
for suite in "${INT_TESTS[@]}"; do
    int_tests=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && int_tests+=("$line")
    done < <(list_int_tests "$suite" || true)
    emit_section "Integration suite \`$suite\`" "cargo test --test $suite" "${int_tests[@]+"${int_tests[@]}"}"
done

echo ""
echo "# Wrote $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes)"
