#!/usr/bin/env python3
"""verify_committed_state_consistency.py — gate that critical paper
files are committed before run_all_checks.sh declares submission-ready.

Loop 134 C operationalizes the "gate green on uncommitted state →
push different state" confusion. Pre-flight check: walks `git status
--porcelain papers/ docs/` and fails on tracked-file modifications
in submission-bound paths.

Rationale: every other CI stage reads the working-tree state of the
paper files. If those files have uncommitted modifications and the
operator pushes the *committed* state (or pulls a clean checkout
elsewhere), the gates would re-run against a different state than
the one they just declared green. This gate forces the operator to
commit before claiming the gate passed.

Scope: tracked-file modifications under `papers/` and `docs/`.
(`papers/scripts/` is already under `papers/` — listing it
separately would be redundant.) Untracked files are allowed by
default (working-tree artifacts, generated outputs not yet
ignored); `--fail-on-untracked` flips that for strict pre-flight.

The gate also explicitly excludes paths the parallel agent work uses
(via the EXCLUDE_PATHS list) so a clean F2-paper commit isn't
blocked by submodule's uncommitted `src/` modifications.

Usage:
  papers/scripts/verify_committed_state_consistency.py
  papers/scripts/verify_committed_state_consistency.py --fail-on-untracked
  papers/scripts/verify_committed_state_consistency.py --staged-only

Exit 0 on clean tracked state; 1 on modified/staged/deleted tracked
files in scope.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parents[2]

# Scope: tracked files under these directories must be committed.
# Anything outside is out of scope (e.g., src/, data/).
SCOPE_PREFIXES = ["papers/", "docs/"]

# Paths to explicitly exclude even when under a SCOPE_PREFIXES entry.
# The auto-generated CHANGELOG section7 file regenerates on every
# `regen_changelog_section7.py` run; treating it as a tracked file
# whose drift must be committed would force a no-op commit on every
# CI cycle.
EXCLUDE_PATHS = {
    "papers/CHANGELOG_section7_generated.md",
    # Loop 135 — 58th-pass SEV-4 fix #10: auto-regenerated by
    # cross_reference_audit.py. If a future operator commits these
    # for archival, every CI run would mark them dirty.
    "papers/cross_reference_report.md",
    "papers/phi_ladder_paper_intro_draft_cross_reference_report.md",
    # Loop 136 — 59th-pass SEV-3 fix #2: rewritten by stage 18's
    # generate_appendix_d.sh with an embedded UTC timestamp on every
    # CI run; would force a no-op commit on every cycle otherwise.
    "papers/appendix_d_test_inventory.md",
}


def porcelain_lines() -> list[str]:
    """Return raw `git status --porcelain` output lines."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, check=True,
            cwd=str(CRATE_ROOT),
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"# FAIL  git status failed: {e}", file=sys.stderr)
        return []
    return [ln for ln in result.stdout.splitlines() if ln]


def staged_paths() -> set[str]:
    """Loop 136 C: return set of relative paths currently in the
    git index (`git diff --name-only --cached`)."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "--cached"],
            capture_output=True, text=True, check=True,
            cwd=str(CRATE_ROOT),
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"# FAIL  git diff --cached failed: {e}", file=sys.stderr)
        return set()
    return {ln.strip() for ln in result.stdout.splitlines() if ln.strip()}


def working_tree_modified_paths() -> set[str]:
    """Return set of relative paths with working-tree mods vs index
    (`git diff --name-only`). Distinct from staged_paths."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only"],
            capture_output=True, text=True, check=True,
            cwd=str(CRATE_ROOT),
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return set()
    return {ln.strip() for ln in result.stdout.splitlines() if ln.strip()}


def in_scope(rel_path: str) -> bool:
    if rel_path in EXCLUDE_PATHS:
        return False
    return any(rel_path.startswith(p) for p in SCOPE_PREFIXES)


def main() -> int:
    # Loop 135 — 58th-pass SEV-4 fix #9: removed dead `--allow-untracked`
    # flag (it was action="store_true" with default=True — never read).
    # The lone flag now is `--fail-on-untracked` which flips the default
    # untracked-OK semantics to untracked-FAIL for strict pre-flight.
    parser = argparse.ArgumentParser()
    parser.add_argument("--fail-on-untracked", action="store_true",
                        help="Untracked tracked-scope paths fail the "
                             "gate (default: untracked is allowed).")
    parser.add_argument(
        "--staged-only", action="store_true",
        help="Loop 136 C: assert that every working-tree-modified file "
             "in scope is ALSO in the git index. Use this after "
             "`git add` to verify the staging is complete before "
             "commit. Passes during mid-loop edit cycles where "
             "porcelain reports modifications but they're all staged."
    )
    args = parser.parse_args()
    untracked_fails = args.fail_on_untracked

    # Loop 136 C: staged-only mode. Check that every working-tree-
    # modified scope file is in the index; succeed if staging is
    # complete even when porcelain shows pending changes.
    if args.staged_only:
        wt_mod = {p for p in working_tree_modified_paths() if in_scope(p)}
        staged = {p for p in staged_paths() if in_scope(p)}
        unstaged = wt_mod - staged
        if unstaged:
            for p in sorted(unstaged):
                print(f"# FAIL  staged-only: working-tree modified "
                      f"but not staged: {p}", file=sys.stderr)
            print(f"# verify_committed_state_consistency.py "
                  f"--staged-only — {len(unstaged)} unstaged "
                  "modification(s) in scope. Run `git add` to stage "
                  "them or revert if unintended.",
                  file=sys.stderr)
            return 1
        print(f"# verify_committed_state_consistency.py --staged-only "
              f"— all {len(wt_mod)} scope-file modification(s) are "
              "staged (ready to commit)")
        return 0

    lines = porcelain_lines()
    if not lines:
        # No modifications at all — clean state.
        print("# verify_committed_state_consistency.py — no modifications "
              "in any scope; tree is clean")
        return 0

    violations: list[str] = []
    skipped = 0
    for raw in lines:
        # Porcelain format: XY <path>  where XY is a 2-char status code.
        # X = staged, Y = working-tree. `??` = untracked.
        status = raw[:2]
        rel_path = raw[3:]
        # Handle renames "R  old -> new" — take the new path.
        if " -> " in rel_path:
            rel_path = rel_path.split(" -> ", 1)[1]
        if not in_scope(rel_path):
            skipped += 1
            continue
        if status == "??":
            if untracked_fails:
                violations.append(f"untracked tracked-scope path: {rel_path}")
            else:
                # Allowed under default.
                pass
            continue
        # Any other status code means tracked + modified/staged/deleted.
        violations.append(f"{status} {rel_path}")

    if violations:
        for v in violations:
            print(f"# FAIL  uncommitted: {v}", file=sys.stderr)
        print(f"# verify_committed_state_consistency.py — "
              f"{len(violations)} uncommitted change(s) in scope "
              f"(papers/ + docs/). Commit before declaring submission-"
              f"ready; gates run against working-tree, not HEAD.",
              file=sys.stderr)
        return 1
    print(f"# verify_committed_state_consistency.py — all tracked "
          f"paper/doc files are committed ({skipped} out-of-scope "
          f"modification(s) ignored)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
