#!/usr/bin/env python3
"""verify_paper_metadata.py — CI-style gate against drift.

Checks four invariants that have all silently broken at least once
across the loops:

1. **Title parity**: the paper's H1 title matches the title field in
   `papers/tmlr_submission_kit/eoi_form_text.md`.
2. **Lib test count parity**: the paper's "exits 0 with NNN passing
   tests" claim matches the actual count from
   `papers/appendix_d_test_inventory.md` (auto-generated by
   `generate_appendix_d.sh`).
3. **arXiv → BibTeX completeness**: every `arXiv:NNNN.NNNNN` cite in
   the paper has a corresponding `@article{arxiv:NNNN.NNNNN, …}` entry
   in `papers/tmlr_submission_kit/f2_methodology.bib`.
4. **Figure count parity**: every "Figure N" referenced in the paper
   has a `papers/figures/figN_*.{png,py}` file present.

Exit 0 = clean. Exit 1 = any violation, with details on stderr.

Usage: papers/scripts/verify_paper_metadata.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parents[2]
PAPER = CRATE_ROOT / "papers" / "f2_methodology.md"
EOI = CRATE_ROOT / "papers" / "tmlr_submission_kit" / "eoi_form_text.md"
BIB = CRATE_ROOT / "papers" / "tmlr_submission_kit" / "f2_methodology.bib"
APPX_D = CRATE_ROOT / "papers" / "appendix_d_test_inventory.md"
FIG_DIR = CRATE_ROOT / "papers" / "figures"


def check_title_parity() -> list[str]:
    errs: list[str] = []
    paper_h1 = None
    for line in PAPER.read_text().splitlines():
        if line.startswith("# "):
            paper_h1 = line[2:].strip()
            break
    if paper_h1 is None:
        errs.append("paper has no H1 title")
        return errs
    # EOI title is the line after "**Title**:".
    eoi = EOI.read_text()
    m = re.search(r"\*\*Title\*\*:\s*(.+?)(?=\n\n|\*\*)", eoi, re.DOTALL)
    if not m:
        errs.append("eoi_form_text.md has no **Title**: field")
        return errs
    eoi_title = re.sub(r"\s+", " ", m.group(1).strip())
    paper_norm = re.sub(r"\s+", " ", paper_h1)
    if paper_norm != eoi_title:
        errs.append(
            f"title mismatch:\n"
            f"  paper  H1:    {paper_norm!r}\n"
            f"  EOI Title:    {eoi_title!r}"
        )
    return errs


def check_test_count_parity() -> list[str]:
    errs: list[str] = []
    paper = PAPER.read_text()
    # Find "NNN passing tests" in §3.5.4 + Appendix A patterns.
    paper_counts = set(re.findall(r"(\d{3,5}) passing tests", paper))
    paper_lib_counts = set(re.findall(r"(\d{3,5}) in `src/lib\.rs`", paper))
    # Appendix D total: counts table rows in the inventory.
    inventory = APPX_D.read_text()
    actual_count = sum(1 for line in inventory.splitlines() if re.match(r"^\| \d+ \|", line))
    # The paper's "passing tests" claims are for cargo test --lib only
    # (632 / 710 / etc.). The inventory total includes binaries and
    # integration suites. Use the lib count from the inventory's
    # "Library" section.
    lib_section = re.search(
        r"### Library \(`src/lib\.rs`\)\s*\n\s*\n_(\d+) tests",
        inventory,
    )
    actual_lib = int(lib_section.group(1)) if lib_section else None
    if paper_counts and actual_lib is not None:
        # The paper claims should match the lib count (the §3.5.4 claim
        # is about `cargo test --lib` specifically).
        for claim in paper_counts:
            if int(claim) != actual_lib:
                errs.append(
                    f"lib test count drift: paper says {claim} passing, "
                    f"inventory says {actual_lib}"
                )
    if paper_lib_counts and actual_lib is not None:
        for claim in paper_lib_counts:
            if int(claim) != actual_lib:
                errs.append(
                    f"lib test count drift (in `src/lib.rs` claim): "
                    f"paper says {claim}, inventory says {actual_lib}"
                )
    # Also check the total inventory count claim.
    total_claims = re.findall(r"lists (\d{3,5}) tests", paper)
    for claim in total_claims:
        if int(claim) != actual_count:
            errs.append(
                f"total inventory drift: paper says {claim} tests in "
                f"the auto-generated inventory, actual is {actual_count}"
            )
    return errs


def check_bib_completeness() -> list[str]:
    errs: list[str] = []
    paper_cites = set(re.findall(r"arXiv:(\d{4}\.\d{4,5})", PAPER.read_text()))
    bib_text = BIB.read_text()
    bib_keys = set(re.findall(r"@\w+\{arxiv:(\d{4}\.\d{4,5})", bib_text))
    missing = paper_cites - bib_keys
    if missing:
        errs.append(
            f"BibTeX missing {len(missing)} arXiv entries cited in paper: "
            f"{sorted(missing)}"
        )
    return errs


def check_figure_files_exist() -> list[str]:
    errs: list[str] = []
    paper = PAPER.read_text()
    refs = set(re.findall(r"\b[Ff]igure (\d+)\b", paper))
    for ref in sorted(int(r) for r in refs):
        glob_pattern = f"fig{ref}_*.png"
        matches = list(FIG_DIR.glob(glob_pattern))
        if not matches:
            errs.append(f"Figure {ref} referenced but no {glob_pattern} in {FIG_DIR}")
    return errs


def main() -> int:
    all_errs: list[tuple[str, list[str]]] = []
    for name, fn in (
        ("title parity", check_title_parity),
        ("test count parity", check_test_count_parity),
        ("BibTeX completeness", check_bib_completeness),
        ("figure files exist", check_figure_files_exist),
    ):
        errs = fn()
        all_errs.append((name, errs))

    total = sum(len(e) for _, e in all_errs)
    print(f"# verify_paper_metadata.py — {total} drift errors")
    for name, errs in all_errs:
        if not errs:
            print(f"  PASS  {name}")
        else:
            for e in errs:
                print(f"  FAIL  {name}: {e}", file=sys.stderr)
    return 0 if total == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
