#!/usr/bin/env bash
#
# Reproducible release build: strip the builder's home directory out of the
# binary so a SECOND laboratory can obtain the same trainer.sha256.
#
# Why this exists
# ---------------
# `ckpt_replay` refuses to execute anything unless the trainer it is handed
# hashes to the `trainer.sha256` recorded in the sidecar. That is the right
# behaviour -- it closes executor substitution -- but it also means the L3
# verdict defined in docs/REPRODUCIBILITY-GRADING.md is only reachable by
# whoever can rebuild that exact binary. Before this script, nobody else could:
#
#   strings -a target/release/trios-train | grep -c '/Users/playra'   ->   588
#
# 588 absolute paths of the ORIGINAL BUILDER were baked into .rodata (504 of
# them under .cargo/registry, the rest the crate's own source paths, mostly via
# panic location strings). An auditor with identical sources, an identical
# `Cargo.lock --locked` and the pinned rustc from rust-toolchain.toml still got
# a different binary, purely because their $HOME spells differently. Same
# inputs, different hash, no verdict.
#
# The fix is `--remap-path-prefix`: rustc rewrites each path prefix it would
# otherwise embed. Three prefixes cover all 588 -- the checkout, the cargo
# registry, and the rustup toolchain.
#
# Why this WRITES .cargo/config.toml instead of only exporting RUSTFLAGS
# ---------------------------------------------------------------------
# RUSTFLAGS only affects the process that exported it. Anyone (or any other
# agent) running a plain `cargo build` in this checkout would compile with
# DIFFERENT flags into the SAME shared target/ directory, and cargo would
# rebuild the world on every alternation between the two fingerprints. On a
# machine that already ran out of disk once, that thrash is not cosmetic. So
# the same expanded flags are persisted into .cargo/config.toml, which every
# cargo invocation in this directory picks up automatically.
#
# The generated file is machine-specific BY CONSTRUCTION: it contains this
# host's expanded absolute paths. It is gitignored (.gitignore:34) and must
# stay that way -- committing it would hand the next laboratory a config
# describing a $HOME that does not exist there. Re-run this script instead.
#
# Usage:  bash scripts/repro_build.sh [extra cargo args...]

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

CARGO_DIR="${CARGO_HOME:-$HOME/.cargo}"
RUSTUP_DIR="${RUSTUP_HOME:-$HOME/.rustup}"

# Each prefix is registered in BOTH its literal and its symlink-resolved form,
# because cargo does not treat the two consistently and picking one is a coin
# flip that fails silently.
#
# Measured, not assumed. Building this tree from /tmp on macOS (where /tmp is a
# symlink to /private/tmp) with CARGO_HOME=/tmp/lab-beta-cargo:
#   - the workspace reached rustc CANONICALISED   (/private/tmp/lab-src/...)
#   - CARGO_HOME reached rustc LITERAL            (/tmp/lab-beta-cargo/...)
# A run that remapped only the canonical form left 503 registry paths in the
# binary and produced a different sha256 from the run next to it. Registering
# both forms costs two extra flags and removes the whole failure mode.
REMAP_ARGS=()
add_remap() {
    local path="$1" alias="$2" resolved
    [ -n "$path" ] || return 0
    REMAP_ARGS+=("--remap-path-prefix=$path=$alias")
    resolved="$( ( cd "$path" 2>/dev/null && pwd -P ) || true )"
    if [ -n "$resolved" ] && [ "$resolved" != "$path" ]; then
        REMAP_ARGS+=("--remap-path-prefix=$resolved=$alias")
    fi
}

add_remap "$ROOT"       /build
add_remap "$CARGO_DIR"  /cargo
add_remap "$RUSTUP_DIR" /rustup

# RUSTFLAGS is space-separated with no quoting mechanism, so a path containing
# a space cannot be expressed here at all. Fail loudly rather than emit flags
# that would be split into nonsense.
for arg in "${REMAP_ARGS[@]}"; do
    case "$arg" in
        *" "*) echo "repro_build: path contains a space, cannot remap: $arg" >&2; exit 1 ;;
    esac
done

export RUSTFLAGS="${REMAP_ARGS[*]}"

REMAP_TOML=""
for arg in "${REMAP_ARGS[@]}"; do
    REMAP_TOML="$REMAP_TOML    \"$arg\",
"
done

mkdir -p "$ROOT/.cargo"
cat > "$ROOT/.cargo/config.toml" <<EOF
# GENERATED by scripts/repro_build.sh -- do not edit by hand, do not commit.
#
# This file is MACHINE-SPECIFIC BY CONSTRUCTION: the paths below are this
# host's expanded \$HOME, \$CARGO_HOME and \$RUSTUP_HOME. It exists so that a
# plain \`cargo build\` in this checkout produces the same binary as
# scripts/repro_build.sh, rather than a second fingerprint that fights the
# first over the shared target/ directory.
#
# The flags rewrite these prefixes to /build, /cargo and /rustup before rustc
# embeds them, so the builder's home directory does not end up in .rodata.
# That removes the blocker; it is NOT by itself a third-party reproduction.
# Measured on macOS, two labs still differ in the 16-byte Mach-O LC_UUID and
# the code signature over it. See docs/REPRODUCIBILITY-GRADING.md.
#
# Regenerate with: bash scripts/repro_build.sh
[build]
rustflags = [
$REMAP_TOML]
EOF

# SOURCE_DATE_EPOCH is exported for any dependency build script that honours it.
# Stated plainly: rustc itself does not consume it, and this crate has no
# build.rs, so on THIS tree it is a precaution rather than a measured fix. It is
# set from the last commit rather than `now` so repeated builds of the same
# commit agree.
if [ -z "${SOURCE_DATE_EPOCH:-}" ]; then
    SOURCE_DATE_EPOCH="$(git -C "$ROOT" log -1 --pretty=%ct 2>/dev/null || echo 0)"
    export SOURCE_DATE_EPOCH
fi

echo "repro_build: root        $ROOT -> /build"
echo "repro_build: cargo home  $CARGO_DIR -> /cargo"
echo "repro_build: rustup home $RUSTUP_DIR -> /rustup"
echo "repro_build: rustc       $(rustc --version)"
echo "repro_build: wrote       $ROOT/.cargo/config.toml"

cargo build --release --locked "$@"

# Honour CARGO_TARGET_DIR: the two-laboratory check in
# .github/workflows/cross-arch-repro.yml gives each lab its own target dir so
# the builds cannot clobber each other, and hardcoding $ROOT/target made this
# script report "no trios-train" after a build that had in fact succeeded.
BIN="${CARGO_TARGET_DIR:-$ROOT/target}/release/trios-train"
if [ ! -x "$BIN" ]; then
    echo "repro_build: no trios-train at $BIN (pass --bin trios-train?)" >&2
    exit 1
fi

# Measure, do not assert-by-comment. `grep -c` exits 1 on zero matches, which
# is the SUCCESS case here, so it must not trip `set -e`.
#
# All FOUR prefixes are checked, not just $HOME. In the two-laboratory trial
# CARGO_HOME sat outside HOME, and the 503 surviving registry paths were caught
# only because "/tmp/lab-beta-cargo" happens to contain "/tmp/lab-beta" as a
# substring. A guard that passes by coincidence is not a guard.
LEAKS=0
for prefix in "$HOME" "$ROOT" "$CARGO_DIR" "$RUSTUP_DIR"; do
    [ -n "$prefix" ] || continue
    hits="$(strings -a "$BIN" | grep -cF "$prefix" || true)"
    if [ "$hits" != "0" ]; then
        echo "repro_build: LEAK $hits x $prefix"
        LEAKS=$((LEAKS + hits))
    fi
done
SHA="$(shasum -a 256 "$BIN" | cut -d' ' -f1)"

echo "repro_build: home-path hits in trios-train: $LEAKS (must be 0)"
echo "repro_build: sha256 $SHA"
if [ "$LEAKS" != "0" ]; then
    echo "repro_build: FAIL - the builder's home directory is still in the binary" >&2
    exit 1
fi
echo "repro_build: OK - no builder path survives into the binary"
